added support for lightgbm booster
microsoft/hummingbird pull request #540
Opened 2021-08-20 06:34 UTC by marsupialtail

Issue #539 : added support for LightGBM booster

2021-08-20 16:57 UTC, ksaur commented
@marsupialtail Thanks so much for the PR! :) I think there are some lint things to check on in the CI/CD.  

Can you please also add tests inside of [test_lightgbm_converter.py](https://github.com/microsoft/hummingbird/blob/main/tests/test_lightgbm_converter.py) to make sure that all lines of `convert_lgbm_booster` hit coverage?  Thank you! And please let me know if you have questions; happy to help.

2021-08-22 21:44 UTC, marsupialtail commented
I added the tests based on the LGBRanker PR you referred. Not sure if that's what you are looking for.

2021-08-23 16:16 UTC, ksaur commented
@marsupialtail I think there is another lint thing.  (I tried to give permissions so the CI/CD would automatically run for you but it didn't seem to work.)  

PR looks great otherwise!  (cc: @interesaaat any comments? )

2021-08-23 16:18 UTC, ksaur requested changes

2021-08-23 16:18 UTC, ksaur commented on hummingbird/ml/operator_converters/lightgbm.py
> +
Can you please add the docstring info? (see lines 84-94 in this same file)

2021-08-24 21:57 UTC, ksaur commented
Ok I *think* I fixed it so you should be able to run the ci/cd without additional permissions. (Github must have changed some setting, because the subsequent run should have 'just ran')

There's some formatting issue, please take a look. Thanks!

2021-08-29 03:53 UTC, marsupialtail commented
Sorry but I absolutely hate lint. Not sure if I will have too much motivation to finish fixing the lint problems :-(

2021-08-30 01:19 UTC, ksaur approved these changes

2021-08-30 01:19 UTC, merged

2021-08-30 01:19 UTC, ksaur commented
Thanks for the contribution and for sticking with it @marsupialtail !